version: '3.8'

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_api
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: task_management
      DB_USERNAME: rian
      DB_PASSWORD: rian
    depends_on:
      - db

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      NEXT_PUBLIC_API_URL: http://laravel:8000/api
    depends_on:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_task_management
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_management
      MYSQL_USER: rian
      MYSQL_PASSWORD: rian
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_task_management
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata:
